# Generated by Django 5.2.1 on 2025-05-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Username',
        ),
    ]
